index.html

Sorry Tom, the scope of this PR is much bigger than what the branch name suggests. There were more UI/UX responsiveness issues than simply the section with the MSAC image and video.

Msac speakup sections -- vvv READ COMMENT vvv

---

covid19.html

fix - Changed the section id for the anti-black racism guidebook

Updated Covid Page

---

css/bootstrap.css
css/bootstrap.min.css
css/creative.css

fix - Fixed the navbar collapse for smaller screens

Fixed navlinks toggle collapse

---

css/creative.css

fix - Fixed the text on the tiles for more than an app section

Fixed more than an app section

---

index.html

fix - Fixed the image to load properly in the how we can help you section

Fixed the how we can help you image section

---

css/creative.css
jointeam.html

refactor 
- Added back the volunteer square section in the jointeam.html file

Updated the Volunteer Page

---

css/creative.css

style 
- Made scroll bar visible on mobile devices for navbar menu
- Adjusted the padding for subnav menus

Fixed scroll bar visibility on mobile devices for navbar menu

---

covid19.html
css/creative.css
index.html
jointeam.html
team.html
workshops.html

feat 
- Added new social media section in covid19.html
fix
- Condensed the google font links into one link
style
- Fixed some font issues on the team.html page
- Cleaned up styling in covid19.html
Notes
- The styling for the social media section in covid19.html may look broken, but it is fixed in PR #71

Add new social media section for Covid page

---

covid19.html
css/creative.css
index.html
links.html

feat 
- Added the eventbrite section to index.html
fix 
- Updated the accessibility, added the latest eventbrite link and cleaned up the links.html file

Added the Eventbrite section to the home and link page

---

index.html

fix 
- Updated the eventbrite link on the home page
- Commented out the latest event section on the home page

Updated the eventbrite section on the home page

---

links.html

feat 
- Added the GoFundMe link to links.html

Added GoFundMe link to links page

---

covid19.html
css/bootstrap.css
css/bootstrap.min.css
css/creative.css
donate.html
index.html
jointeam.html
team.html
workshops.html

feat 
- Created a new donation page for the gofundme link
- Added a new donate page link to the navbar

Add new donate page

---

index.html

Updating beaver graphic to match website header

Update beaver graphic index.html

---

donate.html
index.html

I started to change the navbar of the homepage from feedback in doc of the Google Drive.
I see that each page .html file has to be altered with the new menu, if the change is approved.
Let me know what you think!

Features navbar

---

index.html

If you have the time @iRTerence I would love your feedback!!
I just wanted to make the forms more apparent, so this button links to that section.
The popups 'bug' still needs to be fixed, there seems to be a lot of css to navigate.

Adds 'how can we help?' button

---

team.html

I updated the bio of Current Team Members to reflect their title changes. I also reordered the Past Team Members alphabetically.

Update to title/bio and reordering of members

---

team.html

I resized Janelle's picture on the Teams page.

Resized Janelle's Picture

---

index.html

I changed "volunteer placement" to "volunteer opportunity" on the homepage to make our services clearer.

Changed "volunteer placement" to "volunteer opportunity" on the Homepage

---

jointeam.html

Added "Social Entrepreneurship Program Lead" to jointeam.html

Added a new position to jointeam.html

---

jointeam.html

Reordered sections so that the paid positions are at the top on jointeam.html.

Updates to the jointeam.html page

---

1gnitefair.html
contactus.html
covid19.html
css/creative.css
donate.html
footer.js
index.html
jointeam.html
js/accordian.js
links.html
news.html
slick-1.8.1/index.html
sponsors.html
survey.html
team.html
timeline.html
updated-donate.html
volunteer-opportunities.html

I have made several changes in the index team.html, donate.html

made several changes

---

css/creative.css
index.html

fix twitter and instagram cut off in portrait mode

twitter ig width styling

---

css/creative.css

I fixed the black background that is produced when text is highlighted

fixed the black background produced when highlighting text

---

1gnitefair.html
index.html
jointeam.html
links.html
news.html
sponsors.html
survey.html
team.html
timeline.html
updated-donate.html
volunteer-opportunities.html

fixed all the meta
removing the board

fixed the meta and removing the board

---

covid19.html
css/creative.css

fixed the widget error  in the covid19.html

fixed the error that was in covid19.html

---

css/creative.css
jointeam.html

updated css:
- aligned the '+' across the job posts
- job posts slide open after 1 click, fixed error where double click was needed.
- adjusted positioning of job post

fix job post css and slide

---

contactus.html
css/creative.css
donate.html
footer.js
index.html
lendahandsurvey.html
volunteer-opportunities.html
workshops.html

Removed the container class from all the pages because it causes a white triangle to appear in mobile view.
Fixed widths and margins of items on many pages that have horizontal overflow on mobile view.

Fix overflow

---

css/creative.css
jointeam.html

add script to active highlight job post in mobile view:
- add active for mobile view in creative.css
- add onclick script to toggle class in jointeam.html

job post highlight

---

jointeam.html

simple if else statement to show "-" while the job post is open and "+" while the job post is closed (not active).

script for + and -

---

change-makers-micro-grants.html

Update to the link, dates and FAQ of the entrepreneurship page.

Entrepreneurship Round 2 Applications

---

change-makers-micro-grants.html

Changed link, program details, email, and important dates.

Entrepreneurship Round 3 Applications

---

contactus.html
covid19.html
css/creative.css
css/volunteer-opportunities.css
donate.html
index.html
jointeam.html
navbar.js
news.html
team.html
timeline.html
volunteer-opportunities.html
workshops.html

Implemented edits specified in the Google Doc 2024-12-23 HH Website - Youth Matching Page Changes to Make.

Volunteer page edits

---

black-youth-outreach-united.html
change-makers-micro-grants.html
coming-soon.html
contactus.html
covid19.html
css/donate.css
donate.html
footer.html
index.html
jointeam.html
lendahandsurvey.html
links.html
navbar.html
news.html
team.html
timeline.html
volunteer-120.html
volunteer-opportunities.html
workshops.html

Added three new sections at the top of donate.html according to the canva design. Also added the mailgo script to every page so the footer's email link works and changed all mailto links into mailgo.

Donate page youth fundraising
